ekf_filter_node:
  ros__parameters:
    frequency: 30.0
    sensor_timeout: 0.1
    two_d_mode: false
    publish_tf: true
    map_frame: map
    odom_frame: odom
    base_link_frame: base_link
    world_frame: odom

    imu0: /raw_imu
    imu0_config: [false, false, false,
                  false, false, false,
                  false, false, false,
                  true, true, true,
                  true, true, true]
    imu0_differential: false
    imu0_relative: true

    odom0: /wheel_encoder_velocity
    odom0_config: [false, false, false,
                   false, false, false,
                   true, true, false,
                   false, false, true,
                   false, false, false]
    odom0_differential: false
    odom0_relative: true
