ekf_filter_node:
  ros__parameters:
    frequency: 30.0
    sensor_timeout: 0.1
    two_d_mode: false
    publish_tf: true
    print_diagnostics: false
    map_frame: map
    odom_frame: odom
    base_link_frame: base_link
    world_frame: odom

    imu0: /imu/data_madgwick
    imu0_config: [false, false, false, # x y z
                  false, false, false, # r p y
                  false, false, false, #vx vy vz
                  true, true, true, # vroll vpitch vyaw
                  true, true, true] # ax ay az
    imu0_differential: false
    imu0_relative: true

    odom0: /wheel_odometry
    odom0_config: [false, false, false,
                   false, false, false,
                   true, true, false,
                   false, false, true,
                   false, false, false]
    odom0_differential: false
    odom0_relative: true
