frequency: 30.0
sensor_timeout: 0.1
two_d_mode: false
publish_tf: true
map_frame: map
odom_frame: odom
base_link_frame: base_link
world_frame: odom

imu0: /raw_imu
imu0_config: [false, false, false, #  x, y, z,
               false, false, false, # roll, pitch, yaw, 
               false, false, false, # vx, vy, vz,
               true, true, true, # vroll, vpitch, vyaw, 
               true, true, true] # ax, ay, az
imu0_differential: false
imu0_relative: true

odom0: /wheel_encoder_velocity
odom0_config: [false, false, false, #  x, y, z, 
               false, false, false, # roll, pitch, yaw, 
               true, true, false, # vx, vy, vz,
               false, false, true, # vroll, vpitch, vyaw, 
               false, false, false] # ax, ay, az
odom0_differential: false
odom0_relative: true
